import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId="962765624064-p4qkev7rg3jo2tt0va47j8t24mmhqd7u.apps.googleusercontent.com">
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </GoogleOAuthProvider>
  );
}
